-- Migration: Seed Data for Development
-- Description: Insert initial data for development and testing
-- Date: 2025-09-05

-- Insert default Toxoid patterns for the knowledge base
INSERT INTO toxoid_patterns (
    pattern_type, name, description, example_code, use_cases, complexity_level,
    memory_impact, cpu_impact, best_practices, 
    pattern_embedding, description_embedding,
    is_official
) VALUES
(
    'system',
    'Entity Creation Pattern',
    'Standard pattern for creating entities with components in Toxoid engine',
    'const entity = world.createEntity();\nworld.addComponent(entity, Position, { x: 100, y: 100 });\nworld.addComponent(entity, Sprite, { texture: "player.png" });',
    ARRAY['player-creation', 'object-spawning', 'initialization'],
    'beginner',
    'low',
    'low',
    'Always add components immediately after entity creation to avoid partial entities in systems',
    -- These would normally be generated by embedding service
    ARRAY[0.1, 0.2, 0.3]::float4[]::vector(3)::vector(1536),
    ARRAY[0.1, 0.2, 0.3]::float4[]::vector(3)::vector(1536),
    true
),
(
    'component',
    'Component Query System',
    'Efficient querying of entities with specific components',
    'const query = world.createQuery([Position, Velocity]);\nquery.forEach((entity, [pos, vel]) => {\n    pos.x += vel.x;\n    pos.y += vel.y;\n});',
    ARRAY['movement-systems', 'physics', 'batch-processing'],
    'intermediate',
    'medium',
    'medium',
    'Cache queries outside of update loops for better performance. Use specific component combinations.',
    ARRAY[0.2, 0.3, 0.4]::float4[]::vector(3)::vector(1536),
    ARRAY[0.2, 0.3, 0.4]::float4[]::vector(3)::vector(1536),
    true
),
(
    'observer',
    'Component Change Observer',
    'React to component additions, removals, or changes',
    'world.onComponentAdded(Health, (entity, health) => {\n    console.log(`Entity ${entity} gained health: ${health.value}`);\n});',
    ARRAY['event-handling', 'state-tracking', 'debugging'],
    'intermediate',
    'low',
    'low',
    'Use observers sparingly as they can impact performance. Prefer polling in systems when possible.',
    ARRAY[0.3, 0.4, 0.5]::float4[]::vector(3)::vector(1536),
    ARRAY[0.3, 0.4, 0.5]::float4[]::vector(3)::vector(1536),
    true
),
(
    'optimization',
    'Object Pool Pattern',
    'Reuse objects to reduce garbage collection in performance-critical code',
    'class BulletPool {\n    constructor() { this.pool = []; }\n    get() { return this.pool.pop() || new Bullet(); }\n    release(bullet) { bullet.reset(); this.pool.push(bullet); }\n}',
    ARRAY['performance', 'memory-management', 'bullet-hell'],
    'advanced',
    'high',
    'low',
    'Use for frequently created/destroyed objects. Always reset object state before returning to pool.',
    ARRAY[0.4, 0.5, 0.6]::float4[]::vector(3)::vector(1536),
    ARRAY[0.4, 0.5, 0.6]::float4[]::vector(3)::vector(1536),
    true
),
(
    'query',
    'Spatial Partitioning Query',
    'Efficiently find entities within a spatial region',
    'const nearbyEntities = world.queryRegion(\n    new Rectangle(player.x - 100, player.y - 100, 200, 200),\n    [Position, Collider]\n);',
    ARRAY['collision-detection', 'ai-vision', 'area-effects'],
    'advanced',
    'high',
    'medium',
    'Use appropriate spatial data structures. Consider query frequency vs. update frequency trade-offs.',
    ARRAY[0.5, 0.6, 0.7]::float4[]::vector(3)::vector(1536),
    ARRAY[0.5, 0.6, 0.7]::float4[]::vector(3)::vector(1536),
    true
);

-- Insert sample game genres and categories for the UI
INSERT INTO community_assets (
    creator_id, name, description, asset_type, tags, file_path, preview_path,
    license, status, reviewed_at
) VALUES
(
    -- This would be a system/admin user UUID in production
    '00000000-0000-0000-0000-000000000000',
    'Basic Player Sprite',
    'A simple 32x32 pixel art character sprite for platformer games',
    'sprite',
    ARRAY['character', 'platformer', 'pixel-art'],
    'community/sprites/basic-player.png',
    'community/previews/basic-player-preview.png',
    'cc0',
    'approved',
    NOW()
),
(
    '00000000-0000-0000-0000-000000000000',
    'Jump Sound Effect',
    'Classic 8-bit jump sound effect',
    'audio',
    ARRAY['sound-effect', '8-bit', 'platformer'],
    'community/audio/jump.wav',
    'community/previews/jump-waveform.png',
    'cc0',
    'approved',
    NOW()
),
(
    '00000000-0000-0000-0000-000000000000',
    'Grass Tileset',
    'Repeatable grass texture tiles for ground surfaces',
    'texture',
    ARRAY['tileset', 'environment', 'grass', 'nature'],
    'community/textures/grass-tileset.png',
    'community/previews/grass-tileset-preview.png',
    'cc_by',
    'approved',
    NOW()
);

-- Insert some sample collections for discoverability
-- Note: These would need actual user IDs in production
/*
INSERT INTO collections (
    creator_id, name, description, is_public
) VALUES
(
    '00000000-0000-0000-0000-000000000000',
    'Beginner Templates',
    'Great starting points for new game developers',
    true
),
(
    '00000000-0000-0000-0000-000000000000',
    'Educational Games',
    'Games designed for learning and teaching',
    true
),
(
    '00000000-0000-0000-0000-000000000000',
    'Pixel Art Showcase',
    'Beautiful pixel art games and assets',
    true
);
*/

-- Update embedding generation timestamp for the patterns
UPDATE toxoid_patterns 
SET updated_at = NOW()
WHERE is_official = true;